# Generated by Django 5.0.6 on 2024-06-07 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=10)),
                ("about", models.TextField()),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("Developer", "Developer"),
                            ("Developer", "Developer"),
                            ("Developer", "Developer"),
                            ("Developer", "Developer"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "comlpany",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.company"
                    ),
                ),
            ],
        ),
    ]
